### ISSUE TITLE
Using last_used_at for expiration rather than created_at

### ISSUE THREAD

**Issue by ASBaj** [laravel/sanctum#113]
Hi guys,

I'm implementing Sanctum in my own application - it's awesome, thank you very much for your hard work.

I was curious as to something - looking through the code, I noticed that the logic for determining if a token is expired uses the created_at value; I was wondering if there are any plans for officially using the last_used_at value instead. This mean that the token would only expire X amount of minutes after it was last used which in my opinion would be more useful. Wondering if anyone else agrees?

Thanks!

**Comment by driesvints** [comment]
No plans for this sorry.

**Comment by iec989** [comment]
Why is that? If you set a token to expire in 1 day, and the user is using the mobile app, it will get logged out because the token has expired based on the creation. Not a good user experience.

At the end you end up creating a middleware to play with the last_used_at. I agree with @ASBaj that last_used_at expiration should be at least an option in the config file.

**Comment by hoRacy** [comment]
+1 ❤️
