### ISSUE TITLE
Http 502 config guard sanctum

### ISSUE THREAD

**Issue by sturn** [laravel/sanctum#117]
- Sanctum Version: 2.1
- Laravel Version: 6.2
- PHP Version: 7.3.10
- Database Driver & Version:

### Description:

Http 502

### Steps To Reproduce:

1. config\sanctum.php
`'guard' => 'sanctum', `

2. middleware
`
Route::middleware('auth:sanctum')->get('/test', function (Request $request) {
    return [];
});
`

### I think
**Compatibility Code**

sanctum/src/Guard.php
demo
```php
    /**
     * Retrieve the authenticated user for the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function __invoke(Request $request)
    {
        $statefulGuard = config('sanctum.guard', 'web');
        if (config("auth.guards.{$statefulGuard}.driver") != 'sanctum' && $user = $this->auth->guard($statefulGuard)->user()) {
            return $this->supportsTokens($user)
                        ? $user->withAccessToken(new TransientToken)
                        : $user;
        }
        ......
     }


```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by AndreiTelteu** [comment]
I have this exact same issue. It took me a few hours to figure it out.

I fixed it by setting `"guard" => null,` in `config/sanctum.php` as this comment suggested: https://github.com/laravel/sanctum/pull/149#issuecomment-1013938482

The problem was that i configured `"guard" => ["sanctum"]` thinking that this is how sanctum gets the logged in user.
This is causing an infinite loop i think: `if ($user = $this->auth->guard($guard)->user()) {` ([Guard.php:57](https://github.com/laravel/sanctum/blob/2.x/src/Guard.php#L57))

A simple improvement idea for sanctum is to check and skip the guard if it's using the sanctum guard (just before line 57).
```php
if (config("auth.guards.$guard.driver") == "sanctum") {
    continue;
}
```

**Comment by diego-lipinski-de-castro** [comment]
just got into this problem today, if it gets too common I think its worth a note or some improvement into the framework

**Comment by olamideog** [comment]
Facing the same issue. Sanctum Guard is web, the guard on the route is auth:sanctum and the config/auth.php is using the default web guard.

**Comment by luanrodrigues** [comment]
same here problem here, solved setting it to null

**Comment by yamenarahman** [comment]
One thing to add here, default guard in `auth.php` must be always `web` even if you don't define a `web` guard.

**Comment by itelmenko** [comment]
Why this issue closed? It will be better resolve it in sanctum
