### ISSUE TITLE
"logoutOtherDevices" doesn't work with Laravel Sanctum

### ISSUE THREAD

**Issue by IlCallo** [laravel/sanctum#142]
- Sanctum Version: 2.3.1
- Laravel Version: 7.11.0
- PHP Version: 7.4.4
- Database Driver & Version: MariaDB 10.4.12

### Description:
`logoutOtherDevices` doesn't work when used in conjunction with Laravel Sanctum.
I'm trying to use it to logout a specific user from all its sessions, yet sessions aren't invalidated.

### Steps To Reproduce:
```php
Auth::guard('web')->setUser(User::find(1))->logoutOtherDevices(Str::random(12));
```

Login with an user, use tinker to run previous command, notice it produces no effect on currently active sessions.

**Comment by Ragash** [comment]
https://laravel.com/docs/7.x/authentication#invalidating-sessions-on-other-devices

have you uncommented the middleware?

**Comment by IlCallo** [comment]
Uncommenting the middeware actually breaks the logout.
Sanctum uses its own Middleware in which "AutenticatesSession" isn't present, and that's probably the reason it fails.
Maybe it could be added in its dynamic Middleware stack

**Comment by Ragash** [comment]
replying in IT for semplicity: 
se leggi le docs, se vuoi utilizzare quel metodo, sei costretto ad abilitare AutenticatesSession middleware.
Sono dipendenti, non c'è altro modo purtroppo.
E si, se lasci Sanctum allo stato brado, assume che il tuo logout sia effettuato sulla sua guard (dove il metodo non esiste) e quindi muore.
la soluzione è semplice:
nel tuo login controller specifica molto banalmente:
```
     /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return \Auth::guard('web');
    }
```
Ovviamente assumendo che tu stia utilizzando il tratto con cui lo scaffolding di laravel viene servito.
prova a fare backtracing dell'errore, cosi capisci bene dove si trova il culprit, le mie assunzione si basano principalmente su esperienza personale (anch'io c ho sbattuto il muso)

**Comment by IlCallo** [comment]
It's simpler for us to discuss in IT, but this won't help next ones hitting this problem, so I'll continue in EN.

I know the feature is tied with AuthenticatesSession, I opened this issue explicitly to make everyone aware this is a missing piece into Sanctum integration with Laravel.

I'm already using a custom logout (the default scaffolded by the Laravel UI doesn't work with Sanctum) which specify the use of "web" guard, the problem arise only when I add the "AuthenticatesSession" middleware.

If anyone made Sanctum work with "logoutOtherDevices", please share your workaround. I'm gonna try to tackle the problem in some days anyway

**Comment by Ragash** [comment]
Sure, good point.

I've relooked at your code and I think the problem is not related to logoutOtherDevice but to te fact that (I'm pretty sure) auth->setUset doesn't touch the session at all.
You have to use the login method for that.
Maybe your test is failing cause there's no session to invalidate?

**Comment by IlCallo** [comment]
> I'm trying to use it to logout a specific user from all its sessions, yet sessions aren't invalidated.

The idea comes from [here](https://github.com/laravel/framework/issues/2444#issuecomment-416876849) and is based on the fact that you logout all other sessions of the user, while you don't have a current session. In this way you're actively removing all its sessions.

It worked in 5.6, maybe something changed in the implementation on this regard in following versions (but missing `AuthenticatesSession` in Sactum middleware seems to be the culprit here).

I tested it with multiple incognito windows open, so I'm sure there were other sessions.

An alternative is to go with something similar to [this one](https://stackoverflow.com/questions/19510220/single-session-login-in-laravel), but I'd prefer to avoid coupling session management with user persisted data on the DB. Especially when there is a built-in feature for this.

**Comment by Ragash** [comment]
Still, if you want to use logoutOtherDevice, you need that middleware.
why?
because the middleware take care of checking the `remember_web `cookie, and invalidate the request if data within it mismatchs.

the best way to solve your problem (i did that way right now in my app, just to test, and also because i would need that functionality) is to create your copy of `AuthenticateSession ` specifying  that the guard to use is "web" (the very same Sanctum uses for auth), like you would do in your login controller as i stated some days ago :) 

And yes, even if Sanctum is a guard on it own, it's wrap around the sessionGuard to functioning, so or you couple the session management (nope, don't do that), or simply create your `AuthenticateSession ` middleware as long the devs wont come out with a better solution (maybe a sanctum specific logoutOtherDevice method ? who knows)

hope this helps

**Comment by Ragash** [comment]
Ah, i almost forgot.
Even if you are making a SPA, you would need `AuthenticateSession `in your web middleware anyway.

1) when user load you app: for checking the remember_web cookie, and init stuff.
2) in your api, yep, even if it may seems strange (it is to me), that's because Sanctum on first-party SPA uses session for auths, so if you dont authenticate it, you cannot use it's own function from an api :)

**Comment by driesvints** [comment]
These features are incompatible unfortunately. If you can think of a good solution for this feel free to send in a pr. Thanks.

**Comment by Abhi0725** [comment]
@driesvints Shouldn't issue be closed when it's resolved? 🤔

**Comment by housanpai** [comment]
> I guess what he meant was "won't fix, but go ahead and give a try if you wish"

This is not good news.

It's a question that's been bothering me as well.

**Comment by bondansebastian** [comment]
For anybody encountering this problem, I've managed to find a work around here: https://stackoverflow.com/questions/65623617/logoutotherdevices-isnt-working-with-laravel-sanctum/70469518#70469518

**Comment by vardtheo** [comment]
https://www.youtube.com/watch?v=iwq5YrNND0k

**Comment by htv-quanth** [comment]
Has the problem been solved?
