### ISSUE TITLE
Type error caused by PersonalAccessToken and Model type mismatch

### ISSUE THREAD

**Issue by kayandra** [laravel/sanctum#238]
- Sanctum Version: 2.8.3
- Laravel Version: 8.12
- PHP Version: 8.0
- Database Driver & Version:

### Description:

Running Sanctum on PHP 8 leads to a fatal error being thrown because the current defined `$casts` property on the `PersonalAccessToken` model does not match. In the PersonalAccessToken model, `$casts` is defined like:

```
    protected $casts = [
        'abilities' => 'json',
        'last_used_at' => 'datetime',
    ];
```

but in the parent model, it's defined like:

```
protected array $casts = [];
```

This little discrepancy leads to this error message:

```
PHP Fatal error:  Type of Laravel\Sanctum\PersonalAccessToken::$casts must be array (as in class Illuminate\Database\Eloquent\Model)
```

The easiest fix would be: 

```
    protected array $casts = [
        'abilities' => 'json',
        'last_used_at' => 'datetime',
    ];
```

But since the current laravel/framework supports php greater than 7.3, and this package is meant to support 7.2+, since both versions don't support type class properties this will cause an error. 

What i'm currently doing is manually fixing the type in the `vendor/**/PersonalAccessToken` file which is a hacky workaround at the momemt.

**Comment by driesvints** [comment]
I'm guessing you mean child model and not parent model. Since the implementing model doesn't implements the array property type you cannot add it in the child model. This is unfortunately how PHP works and we aren't going to be adding these properties ourselves anytime soon. We still need to support PHP 7.3 for example.

**Comment by kayandra** [comment]
I mean the parent model from laravel itself defines the type not a child model

**Comment by driesvints** [comment]
> I mean the parent model from laravel itself defines the type not a child model

Both [the base Eloquent model](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L50) and [Sanctum's PersonalAccessToken mode](https://github.com/laravel/sanctum/blob/2.x/src/PersonalAccessToken.php#L15) don't have this type defined so that's incorrect.

> it's good to hear the changes are coming soon

I said no such thing.
