### ISSUE TITLE
419 Mismatch Error

### ISSUE THREAD

**Issue by mattg66** [laravel/sanctum#296]
- Sanctum Version: 2.11.2
- Laravel Version: 8.51.0
- PHP Version: 8.0.8
- Database Driver & Version: MariaDB 10.3.29

### Description:
Upon every request, the session token is regenerated :
![image](https://user-images.githubusercontent.com/56981878/127131209-8cea2eb6-c031-40e9-83b9-304b9a25b34a.png)
![image](https://user-images.githubusercontent.com/56981878/127131225-8595e671-7536-4d05-85fc-2cd03e6b87fb.png)

As can be seen, the X-XSRF-TOKEN is being sent correctly by the client, however the session token is regenerated upon every request.

To generate the output, I temporarily modified the VerifyCsrfToken.php to show the following:
`protected function tokensMatch($request)
    {
        $token = $this->getTokenFromRequest($request);
        dd(['token' => $token, 'session' => $request->session()->token()]);
        return is_string($request->session()->token()) &&
               is_string($token) &&
               hash_equals($request->session()->token(), $token);
    }`

### Steps To Reproduce:
Install Sanctum, and add the following middleware to the api via Kernel.php:
`'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ],`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by mattg66** [comment]
Hi there, this bug is down to me not properly using the web middleware for the login scree, works as expected now.
