### ISSUE TITLE
SPA auth not working in Safari

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/sanctum#360]
- Sanctum Version: v2.15.1
- Laravel Version: 8.83.8
- PHP Version: 7.4.2
- Database Driver & Version: MySql

### Description:
Given: An api runs at `api.example.com` and an app runs at `app.example.com`, where the api is used for spa authentication.

SPA-auth does not work in Safari. There are some same-site cookie issues there.

### Steps To Reproduce:

- install laravel + sanctum
- install nuxt + nuxt-auth
- run them under different subdomains
- try to login with safari (13, 14, 15) on mac

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Tbvh, this more seems like a support question. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
