### ISSUE TITLE
Sanctum is returning first and wrong user without middleware and using `Auth::guard('sanctum')`

### ISSUE THREAD

**Issue by mikkpokk** [laravel/sanctum#407]
- Sanctum Version: 3.0.1
- Laravel Version: 9.26.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.21

### Description:

Sometimes, there are necessary to lookup user on public route to return extra user related data. For such a cases we have helper `auth('sanctum')->user()`. However, this helper returns the first user from users table, which is not correct. This user is not even token owner.

### Steps To Reproduce:

* Create public route
* Write callback below:
```php
if (auth('sanctum')->check()) {
     return auth('sanctum')->user();
}

return [];
```
* Visit URL as a guest (acts correctly)
* Visit URL with a Bearer token (returns always first user from the table)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Are you applying the `auth:sanctum` middleware?

**Comment by mikkpokk** [comment]
No, that is the case. The route should be public, which is why I cannot apply `auth:sanctum` middleware and have to catch user via `Auth::guard`.

The problem isn't that the user is not found. The problem is that $accessToken->tokenable will load first user from the table which is not associated with the token. I assume `auth:sanctum` middleware does relationship eager loading part but guard doesn't.

**Comment by driesvints** [comment]
You can't both have a public and an authed route with Sanctum. The auth middleware resolves the user. Since you're not using it you're running into the message you indicated.

**Comment by mikkpokk** [comment]
Let's imagine the scenario for a second.

I do have public news route and since Authorization header is passed in I do want to pass in whether the user is the owner of the news post or not.

**You're saying `auth('sanctum')->user()` should not work in that scenario and it is correct that it returns the first user from the database table, who is not the token owner?**

**Comment by mikkpokk** [comment]
I get that, that's why it's used as `Auth::guard('sanctum')->user()` or as a shorthand `auth('sanctum`)->user()`.

It behaves correctly, except it doesn't load the correct relationship without sanctum middleware. As we know, sanctum middleware makes the route private too which is not the goal.
