### ISSUE TITLE
Update to Laravel 11 causes 401 issues when using stateful domains

### ISSUE THREAD

**Issue by likeadeckofcards** [laravel/sanctum#503]
### Sanctum Version

4.0.0

### Laravel Version

11.0.7

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

When updating to Laravel 11, if you remove the app config file but leave the sanctum file the call to `Sanctum::currentApplicationUrlWithPort()` will cause the underlying fetch of `config('app.url')` will result in a null value being returned.

So far I have found 2 workarounds:
1. Remove the sanctum.php or at least remove the definition of `stateful` from the file.
2. Make sure to define the `SANCTUM_STATEFUL_DOMAINS` in the env file.

### Steps To Reproduce

1. Upgrade from Laravel 10 to Laravel 11.
2. Remove the app.php config file (If you use Laravel Shift, this is done for you)
3. Try opening the app using stateful domains without defining `SANCTUM_STATEFUL_DOMAINS` in the `.env` file

**Comment by driesvints** [comment]
> if you remove the app config file 

We don't officially support removing this file. Just leave it in.

**Comment by telkins** [comment]
I am experiencing this problem **with** the app config file.

We have our `config/app.php` file in place with the the following (default) line:
```
    'url' => env('APP_URL', 'http://localhost'),
```

We have `config/sanctum.php`, too, where we set our stateful URLs.

It does **not** pick up the current application URL.

(It actually seems to pick it up for the "default" sanctum config file, but not the app's sanctum config file, so when they're merged, it seems to hang on to the `null` value instead of the actual current application url string.)

Our current workaround is to hard-code the current application URLs (for the different environments we use).  This is simple enough, but either something is broken or we're doing something wrong.

Any thoughts/advice/suggestions?
