### ISSUE TITLE
Unable to validate password using validation rules

### ISSUE THREAD

**Issue by Mr-wangwei** [laravel/sanctum#510]
php: 8.3
Laravel: 11.2
laravel/sanctum: v4.0.1

Authentication fails when using authentication rule `current_password` to authenticate passwords

<img width="825" alt="image" src="https://github.com/laravel/sanctum/assets/46190162/643eff47-be9f-4cc3-b1a7-5db0527e7741">
<img width="383" alt="image" src="https://github.com/laravel/sanctum/assets/46190162/7b31d099-1dfa-40b5-b760-363aa3962a39">

`config/auth.php`
<img width="401" alt="image" src="https://github.com/laravel/sanctum/assets/46190162/4528c159-c720-4f58-8bcf-9a5122b1266b">

No problem with Hash::check().

`config/sanctum.php`
<img width="728" alt="image" src="https://github.com/laravel/sanctum/assets/46190162/ae44c648-4761-4c84-b20f-23c8aa7e3142">

**Comment by Mr-wangwei** [comment]
'guard' => ['web', 'admin'] This results in an infinite loop

**Comment by RahulDey12** [comment]
@Mr-wangwei what you are doing here is completely wrong this is not the way to authenticate a user. The `current_password` validation rule is for implementing some kind of lockout system rather than the authentication system. `current_password` checks whether the current logged-in user's password matches or not.

To learn more about the authentication system in laravel using sactum is https://laravel.com/docs/11.x/sanctum#issuing-mobile-api-tokens

**Comment by driesvints** [comment]
Thanks @RahulDey12

@Mr-wangwei next time please use the actual issue template when submitting bug reports, thanks.
